<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtbox_message</name>
   <tag></tag>
   <elementGuidId>1157314c-6c28-4fd9-b3f2-6cd3f61d3e67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[id=&quot;post_textbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1591105877635</value>
   </webElementProperties>
</WebElementEntity>
